# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QkLoeuFxPupqwosabbkVcT_YYnSBG1S7
"""

#!pip install tensorflow-model-garden
!pip install tf-models-official

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

# Commented out IPython magic to ensure Python compatibility.
# %tensorflow_version 2.x  # this line is not required unless you are in a notebook
import tensorflow as tf
import tensorflow_datasets as tfds
from tensorflow.keras.applications import MobileNetV2

from tensorflow.keras import datasets, layers, models
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.models import Model
import matplotlib.pyplot as plt
import numpy as np
#import tensorflow_addons as tfa

import tensorflow_models as tfm

# split the data manually into 80% training, 10% testing, 10% validation
(raw_train, raw_validation, raw_test), metadata = tfds.load(
    'cats_vs_dogs',
    split=['train[:60%]', 'train[60%:80%]', 'train[80%:]'],
    with_info=True,
    as_supervised=True,
)

get_label_name = metadata.features['label'].int2str  # creates a function object that we can use to get labels

# display 2 images from the dataset
for image, label in raw_train.take(2):
  plt.figure()
  plt.imshow(image)
  plt.title(get_label_name(label))

# 2. Preprocess function for the dataset
def preprocess_image(image, label):
    #image = tf.image.resize(image, (160, 160))  # MobileNetV2 expects input size >= 32x32. 96x96 is a good choice.
    image = tf.image.resize_with_pad(image, 160, 160)
    image = tf.keras.applications.mobilenet_v2.preprocess_input(image) # Normalize according to MobileNetV2
    return image, label

# Create a Keras RandomRotation layer outside the map function for efficiency.
rotation_layer = layers.RandomRotation(factor=0.2)

# 2. Define the augmentation function
def augment_data(image, label):
    # Resize the image to a consistent shape
    #image = tf.image.resize(image, [IMG_SIZE, IMG_SIZE])
    # Apply random augmentations
    #image = tf.image.random_flip_left_right(image)
    #image = tf.image.RandomRotation(0.2)
    image = rotation_layer(image)          # Apply layer
    #image = tf.image.random_brightness(image, max_delta=0.2)
    # Add other augmentations as needed
    return image, label

# Define batch size and shuffle buffer size
BATCH_SIZE = 16
SHUFFLE_BUFFER_SIZE = 10000  # A good buffer size for shuffling

# 3. Apply preprocessing, shuffle, and batch
#BATCH_SIZE = 64
#SHUFFLE_BUFFER_SIZE = 1000

raw_train = raw_train.map(preprocess_image, num_parallel_calls=tf.data.AUTOTUNE)
#raw_train = raw_train.shuffle(SHUFFLE_BUFFER_SIZE).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
raw_train = raw_train.shuffle(SHUFFLE_BUFFER_SIZE).map(augment_data, num_parallel_calls=tf.data.AUTOTUNE).repeat(3).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
#ds_train = ds_train.shuffle(SHUFFLE_BUFFER_SIZE).map(augment_data, num_parallel_calls=tf.data.AUTOTUNE).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

raw_validation = raw_validation.map(preprocess_image, num_parallel_calls=tf.data.AUTOTUNE)
#raw_validation = raw_validation.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
raw_validation = raw_validation.batch(BATCH_SIZE).map(augment_data, num_parallel_calls=tf.data.AUTOTUNE).repeat(3).prefetch(tf.data.AUTOTUNE)
#ds_test = ds_test.batch(BATCH_SIZE).map(augment_data, num_parallel_calls=tf.data.AUTOTUNE).prefetch(tf.data.AUTOTUNE)

# 4. Load pre-trained MobileNetV2
base_model = MobileNetV2(input_shape=(160, 160, 3),
                           include_top=False,  # Exclude the top classification layer
                           weights='imagenet') # Use weights pre-trained on ImageNet

# Freeze the base model layers to prevent re-training them initially
base_model.trainable = False

# 5. Add custom classification layers on top of MobileNetV2
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(10, activation='softmax')(x)  # 10 classes for CIFAR-10

model = Model(inputs=base_model.input, outputs=x)

# 6. Compile the model
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

model.compile(optimizer=optimizer,
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# 7. (Optional) Train the model
model.fit(raw_train, epochs=2, validation_data=raw_validation)

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

"""
# Get the first element (image and label) from the training dataset
# .take(1) creates a dataset with a single element
# .as_numpy_iterator() converts the TensorFlow tensors to NumPy arrays
#for image, label in ds_train.take(1).as_numpy_iterator():
for image, label in raw_train.take(1).as_numpy_iterator():
    first_image1 = image
    first_label1 = label

print(f"Shape of the image: {first_image1.shape}")
print(f"Data type of the image: {first_image1.dtype}")

# Display the image
#plt.imshow(first_image, cmap=plt.cm.binary)
plt.imshow(first_image1, cmap=plt.cm.binary)
#plt.title(f"Label: {first_label}")
plt.xlabel(get_label_name(first_label1))
#plt.axis('off')
plt.show()

print(f"Shape of the image: {first_image1.shape}")
print(f"Data type of the image: {first_image1.dtype}")
"""

# Get the first element (image and label) from the training dataset
# .take(1) creates a dataset with a single element
# .as_numpy_iterator() converts the TensorFlow tensors to NumPy arrays
#for image, label in ds_train.take(1).as_numpy_iterator():
for image, label in raw_test.take(35).as_numpy_iterator():
    first_image = image
    first_label = label

# Display the image
#plt.imshow(first_image, cmap=plt.cm.binary)
plt.imshow(first_image, cmap=plt.cm.binary)
#plt.title(f"Label: {first_label}")
plt.xlabel(get_label_name(first_label))
#plt.axis('off')
plt.show()

print(f"Shape of the image: {first_image.shape}")
print(f"Data type of the image: {first_image.dtype}")

#!pip install tensorflow-model-garden
#!pip install tf-models-official



# select the image from our test dataset
#image_number = 35
#x_test = x_test.resize(96, 96)
#pip install tensorflow-model-garden

# display the image
print(f"Shape of the image: {first_image.shape}")
plt.imshow(first_image)
plt.xlabel(get_label_name(first_label))
plt.show()

# Define the rotation angle in degrees
degrees = 180.0
# Rotate the image using tfm.vision.augment.rotate
rotated_image = tfm.vision.augment.rotate(first_image, degrees)
# display the image
print(f"Shape of the image: {rotated_image.shape}")
plt.imshow(rotated_image)
plt.xlabel(get_label_name(first_label))
plt.show()

image_tensor = tf.convert_to_tensor(rotated_image)
res_image = tf.image.resize_with_pad(rotated_image, 160, 160)
resized_image_uint8 = tf.cast(res_image, tf.uint8)

print(f"Shape of the image: {resized_image_uint8.shape}")
plt.imshow(resized_image_uint8)
plt.xlabel(get_label_name(first_label))
plt.show()

# load the image in an array
n = np.array(resized_image_uint8)
print(f"Shape of the image: {n.shape}")
#plt.imshow(resized_image_uint8)
plt.imshow(n)
plt.xlabel(get_label_name(first_label))
plt.show()

# reshape it
#p = n.reshape(1, 96, 96, 3)
# Add batch dimension (for a single image, batch_size = 1)
p = np.expand_dims(n, axis=0) # Shape: (1, height, width, 3)

# pass in the network for prediction and
# save the predicted label
predicted_label = get_label_name(model.predict(p).argmax())

# load the original label
original_label = get_label_name(first_label)

# display the result
print("Original label is {} and predicted label is {}".format(
    original_label, predicted_label))





IMG_SIZE = 160 # All images will be resized to 160x160

def format_example(image, label):
  """
  returns an image that is reshaped to IMG_SIZE
  """
  image = tf.cast(image, tf.float32)
  image = (image/127.5) - 1
  image = tf.image.resize(image, (IMG_SIZE, IMG_SIZE))
  return image, label

"""
## 1. Load the CIFAR10 dataset
(ds_train, ds_test), ds_info = tfds.load(
        'cifar10',
        split=['train', 'test'],
        shuffle_files=True,
        as_supervised=True,  # Returns (image, label) pairs
        with_info=True,
)

ds_test1 = ds_test

# (x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()

class_n =['airplane', 'automobile', 'bird', 'cat', 'deer',
          'dog', 'frog', 'horse', 'ship', 'truck']

"""

# Get the first element (image and label) from the training dataset
# .take(1) creates a dataset with a single element
# .as_numpy_iterator() converts the TensorFlow tensors to NumPy arrays
#for image, label in ds_train.take(1).as_numpy_iterator():
for image, label in ds_test.take(1).as_numpy_iterator():
    first_image = image
    first_label = label

# Display the image
#plt.imshow(first_image, cmap=plt.cm.binary)
plt.imshow(first_image, cmap=plt.cm.binary)
#plt.title(f"Label: {first_label}")
plt.xlabel(class_n[first_label])
#plt.axis('off')
plt.show()

print(f"Shape of the image: {first_image.shape}")
print(f"Data type of the image: {first_image.dtype}")

# Let's look at one image
# IMG_INDEX = 7
# plt.imshow(x_train[IMG_INDEX], cmap=plt.cm.binary)
# plt.xlabel(class_n[y_train[IMG_INDEX][0]])
# plt.show()

# plt.imshow(x_test[IMG_INDEX], cmap=plt.cm.binary)
# plt.xlabel(class_n[y_test[IMG_INDEX][0]])
# plt.show()

## data augmentation
#data_augmentation = tf.keras.Sequential([
#    #tf.keras.layers.RandomFlip("horizontal_and_vertical"),
#    tf.keras.layers.RandomRotation(0.2),
#    #tf.keras.layers.RandomZoom(0.2),
#])

# Create a Keras RandomRotation layer outside the map function for efficiency.
rotation_layer = layers.RandomRotation(factor=0.2)

# 2. Define the augmentation function
def augment_data(image, label):
    # Resize the image to a consistent shape
    #image = tf.image.resize(image, [IMG_SIZE, IMG_SIZE])
    # Apply random augmentations
    #image = tf.image.random_flip_left_right(image)
    #image = tf.image.RandomRotation(0.2)
    image = rotation_layer(image)          # Apply layer
    #image = tf.image.random_brightness(image, max_delta=0.2)
    # Add other augmentations as needed
    return image, label

## Convert to tf.data.Dataset objects
## Note: y_train and y_test are often 2D arrays (N, 1), so flatten them to (N,)
#train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train.flatten()))
#test_dataset = tf.data.Dataset.from_tensor_slices((x_test, y_test.flatten()))

# flatten the label values
# y_train, y_test = y_train.flatten(), y_test.flatten()

# Define batch size and shuffle buffer size
BATCH_SIZE = 64
SHUFFLE_BUFFER_SIZE = 10000  # A good buffer size for shuffling

# Apply shuffling and batching to the training dataset
#ds_train = ds_train.shuffle(SHUFFLE_BUFFER_SIZE).batch(BATCH_SIZE)

# Apply batching to the test dataset (shuffling is typically not needed for evaluation)
#ds_test = ds_test.batch(BATCH_SIZE)

# Optional: Prefetching for performance optimization
# train_dataset = train_dataset.prefetch(tf.data.AUTOTUNE)
# test_dataset = test_dataset.prefetch(tf.data.AUTOTUNE)

# 2. Preprocess function for the dataset
def preprocess_image(image, label):
    image = tf.image.resize(image, (96, 96))  # MobileNetV2 expects input size >= 32x32. 96x96 is a good choice.
    image = tf.keras.applications.mobilenet_v2.preprocess_input(image) # Normalize according to MobileNetV2
    return image, label

# 3. Apply preprocessing, shuffle, and batch
#BATCH_SIZE = 64
#SHUFFLE_BUFFER_SIZE = 1000

ds_train = ds_train.map(preprocess_image, num_parallel_calls=tf.data.AUTOTUNE)
ds_train = ds_train.shuffle(SHUFFLE_BUFFER_SIZE).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
#ds_train = ds_train.shuffle(SHUFFLE_BUFFER_SIZE).map(augment_data, num_parallel_calls=tf.data.AUTOTUNE).repeat(1).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
#ds_train = ds_train.shuffle(SHUFFLE_BUFFER_SIZE).map(augment_data, num_parallel_calls=tf.data.AUTOTUNE).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

ds_test = ds_test.map(preprocess_image, num_parallel_calls=tf.data.AUTOTUNE)
ds_test = ds_test.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
#ds_test = ds_test.batch(BATCH_SIZE).map(augment_data, num_parallel_calls=tf.data.AUTOTUNE).repeat(1).prefetch(tf.data.AUTOTUNE)
#ds_test = ds_test.batch(BATCH_SIZE).map(augment_data, num_parallel_calls=tf.data.AUTOTUNE).prefetch(tf.data.AUTOTUNE)

## 3. Create the data pipeline with on-the-fly augmentation
#ds_train = ds_train.shuffle(ds_info.splits['train'].num_examples) \
#                   .map(augment_data, num_parallel_calls=tf.data.AUTOTUNE) \
#                   .batch(32) \
#                   .repeat() \
#                   .prefetch(tf.data.AUTOTUNE)

# apply preprocessing
# train_dataset = train_dataset.map(preprocess_image, num_parallel_calls=tf.data.AUTOTUNE)

# test_dataset = test_dataset.map(preprocess_image, num_parallel_calls=tf.data.AUTOTUNE)

#x_train, y_train = preprocess_image(x_train, y_train)

#x_test, y_test = preprocess_image(x_test, y_test)

# 4. Load pre-trained MobileNetV2
base_model = MobileNetV2(input_shape=(96, 96, 3),
                           include_top=False,  # Exclude the top classification layer
                           weights='imagenet') # Use weights pre-trained on ImageNet

# Freeze the base model layers to prevent re-training them initially
base_model.trainable = False

# 5. Add data augmentation layer, the pre-trained based model, and new classification layers
#inputs = tf.keras.Input(shape=(96, 96, 3))
#x = data_augmentation(inputs)
##x = tf.keras.applications.mobilenet_v2.preprocess_input(x)

#x = base_model(x, training=False)
#x = tf.keras.layers.GlobalAveragePooling2D()(x)
#x = Dense(10, activation='softmax')(x)  # 10 classes for CIFAR-10

#model = Model(inputs, outputs=x)

# 5. Add custom classification layers on top of MobileNetV2
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(10, activation='softmax')(x)  # 10 classes for CIFAR-10

model = Model(inputs=base_model.input, outputs=x)

# 6. Compile the model
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

model.compile(optimizer=optimizer,
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# 7. (Optional) Train the model
model.fit(ds_train, epochs=3, validation_data=ds_test)

# Get the first element (image and label) from the training dataset
# .take(1) creates a dataset with a single element
# .as_numpy_iterator() converts the TensorFlow tensors to NumPy arrays
#for image, label in ds_train.take(1).as_numpy_iterator():
for image, label in ds_test1.take(1).as_numpy_iterator():
    first_image = image
    first_label = label

# Display the image
#plt.imshow(first_image, cmap=plt.cm.binary)
plt.imshow(first_image, cmap=plt.cm.binary)
#plt.title(f"Label: {first_label}")
plt.xlabel(class_n[first_label])
#plt.axis('off')
plt.show()

print(f"Shape of the image: {first_image.shape}")
print(f"Data type of the image: {first_image.dtype}")

# Distribute it to train and test set
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()
print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

# flatten the label values
y_train, y_test = y_train.flatten(), y_test.flatten()

#x_test = x_test.map(preprocess_image, num_parallel_calls=tf.data.AUTOTUNE)

# select the image from our test dataset
image_number = 35
#x_test = x_test.resize(96, 96)

# display the image
plt.imshow(x_test[image_number])

# load the image in an array
n = np.array(x_test[image_number])
print(f"Shape of the image: {n.shape}")
#n = n.resize((96, 96))
n = tf.image.resize(n, [96, 96])
print(f"Shape of the image: {n.shape}")

# reshape it
#p = n.reshape(1, 96, 96, 3)
# Add batch dimension (for a single image, batch_size = 1)
p = np.expand_dims(n, axis=0) # Shape: (1, height, width, 3)

# pass in the network for prediction and
# save the predicted label
predicted_label = class_n[model.predict(p).argmax()]

# load the original label
original_label = class_n[y_test[image_number]]

# display the result
print("Original label is {} and predicted label is {}".format(
    original_label, predicted_label))

# Convert the dataset to an iterable of NumPy arrays
ds_numpy = tfds.as_numpy(ds_test1)

# Iterate and access the NumPy arrays
for example in ds_numpy:
    #image_array = example['image']
    #label_array = example['label']
    image_array = example[1]
    label_array = example[0]
    #print(f"Image shape: {image_array.shape}, Label: {label_array}")
    # You can now work with image_array as a standard NumPy array

# Convert the dataset to an iterable of NumPy arrays
ds_numpy = tfds.as_numpy(ds_test1)

# Access the first image and its label
for image, label in ds_numpy:
    first_image = image
    first_label = label
    break # Exit after getting the first element

# Display the first image
plt.imshow(first_image, cmap=plt.cm.binary) # Use cmap for grayscale images like MNIST
plt.title(f"Label: {first_label}")
plt.xlabel(class_n[first_label])
#plt.axis('off') # Hide axes for cleaner image display
plt.show()

print(f"Shape of the image: {first_image.shape}")
print(f"Data type of the image: {first_image.dtype}")

# Iterate through the dataset and convert to NumPy
for image, label in ds_test1:
    image_np = image.numpy()
    label_np = label.numpy()
    #print(f"Batch image shape: {image_np.shape}, Batch label shape: {label_np.shape}")
    # image_np and label_np are now NumPy arrays

# Iterate through the dataset and convert to NumPy
for image_batch, label_batch in ds_test1:
    image_np = image_batch.numpy()
    label_np = label_batch.numpy()
    #print(f"Batch image shape: {image_np.shape}, Batch label shape: {label_np.shape}")
    # image_np and label_np are now NumPy arrays

# select the image from our test dataset
image_number = 0

# display the image
plt.imshow(image_np[image_number])

# load the image in an array
n = np.array(image_np[image_number])

# reshape it
p = n.reshape(1, 96, 96, 3)

# pass in the network for prediction and
# save the predicted label
predicted_label = class_n[model.predict(p).argmax()]

# load the original label
original_label = class_n[y_test[image_number]]

# display the result
print("Original label is {} and predicted label is {}".format(
    original_label, predicted_label))

# Convert the dataset to an iterable of NumPy arrays
ds_numpy = tfds.as_numpy(ds_test1)

# Iterate and access the NumPy arrays
for example in ds_numpy:
    #image_array = example['image']
    #label_array = example['label']
    image_array = example[1]
    label_array = example[0]
    print(f"Image shape: {image_array.shape}, Label: {label_array}")
    # You can now work with image_array as a standard NumPy array

# select the image from our test dataset
image_number = 0

# display the image
plt.imshow(x_test[image_number])

# load the image in an array
n = np.array(x_test[image_number])
p = p.resize(96, 96)

# reshape it
p = n.reshape(1, 96, 96, 3)

# pass in the network for prediction and
# save the predicted label
predicted_label = labels[model.predict(p).argmax()]

# load the original label
original_label = labels[y_test[image_number]]

# display the result
print("Original label is {} and predicted label is {}".format(
    original_label, predicted_label))

# Convert the dataset to an iterable of NumPy arrays
ds_numpy = tfds.as_numpy(ds_test1)

# Iterate and access the NumPy arrays
for example in ds_numpy:
    #image_array = example['image']
    #label_array = example['label']
    image_array = example[1]
    label_array = example[0]
    print(f"Image shape: {image_array.shape}, Label: {label_array}")
    # You can now work with image_array as a standard NumPy array

# select the image from our test dataset
image_number = 0

# display the image
plt.imshow(image_array[image_number])

# load the image in an array
n = np.array(image_array[image_number])

# reshape it
p = n.reshape(1, 32, 32, 3)

# pass in the network for prediction and
# save the predicted label
predicted_label = class_n[model.predict(p).argmax()]

# load the original label
original_label = class_n[label_array[image_number]]

# display the result
print("Original label is {} and predicted label is {}".format(
    original_label, predicted_label))

p = first_image.copy()
p = p.resize(96, 96)
p = np.array(p)
# reshape it
p = p.reshape(1, 96, 96, 3)

# pass in the network for prediction and
# save the predicted label
predicted_label = class_n[model.predict(p).argmax()]

# load the original label
original_label = class_n[label_arrasy[first_label]]

# display the result
print("Original label is {} and predicted label is {}".format(
    original_label, predicted_label))

# Convert the dataset to an iterable of NumPy arrays
ds_numpy = tfds.as_numpy(ds_test)

# Access the first image and its label
for image, label in ds_numpy:
    first_image = image
    first_label = label
    break # Exit after getting the first element

# Display the first image
plt.imshow(first_image, cmap=plt.cm.binary) # Use cmap for grayscale images like MNIST
#plt.title(f"Label: {first_label}")
#plt.axis('off') # Hide axes for cleaner image display
plt.show()

# Get the first element (image and label) from the dataset
#first_example = next(iter(ds_test))

# The first element of the tuple is the image, the second is the label
#first_image_np = first_example[0]
#first_label_np = first_example[1]

#print(f"Shape of the first image: {first_image_np.shape}")
#print(f"Type of the first image: {type(first_image_np)}")
#print(f"Label of the first image: {first_label_np}")

# Display the image
#plt.imshow(first_image, cmap=plt.cm.binary)
#plt.imshow(first_image_np, cmap=plt.cm.binary)
#plt.title(f"Label: {first_label}")
#plt.xlabel(class_n[first_label_np])
#plt.axis('off')
#plt.show()

#print(f"Shape of the image: {first_image.shape}")
#print(f"Data type of the image: {first_image.dtype}")

# Get the first element (image and label) from the training dataset
# .take(1) creates a dataset with a single element
# .as_numpy_iterator() converts the TensorFlow tensors to NumPy arrays
#for image, label in ds_train.take(1).as_numpy_iterator():
for image, label in ds_test.take(1).as_numpy_iterator():
    first_image = image
    first_label = label

# Display the image
#plt.imshow(first_image, cmap=plt.cm.binary)
plt.imshow(first_image, cmap=plt.cm.binary)
#plt.title(f"Label: {first_label}")
plt.xlabel(class_n[first_label])
#plt.axis('off')
plt.show()

print(f"Shape of the image: {first_image.shape}")
print(f"Data type of the image: {first_image.dtype}")

# 8. Evaluate
model.evaluate(ds_test, verbose=2, return_dict=True)





BATCH_SIZE = 32
    SHUFFLE_BUFFER_SIZE = ds_info.splits['train'].num_examples # For full shuffling

    ds_train = ds_train.map(preprocess, num_parallel_calls=tf.data.AUTOTUNE)
    ds_train = ds_train.cache() # Cache after preprocessing for faster epochs
    ds_train = ds_train.shuffle(SHUFFLE_BUFFER_SIZE)
    ds_train = ds_train.batch(BATCH_SIZE)
    ds_train = ds_train.prefetch(tf.data.AUTOTUNE) # Prefetch batches for performance



#  LOAD AND SPLIT DATASET
(train_images, train_labels), (test_images, test_labels) = datasets.cifar10.load_data()

# Normalize pixel values to be between 0 and 1
train_images, test_images = train_images / 255.0, test_images / 255.0

class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer',
               'dog', 'frog', 'horse', 'ship', 'truck']

# Let's look at a one image
IMG_INDEX = 7  # change this to look at other images

plt.imshow(train_images[IMG_INDEX] ,cmap=plt.cm.binary)
plt.xlabel(class_names[train_labels[IMG_INDEX][0]])
plt.show()

model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))

model.summary()  # let's have a look at our model so far

model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10))

model.summary()

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

history = model.fit(train_images, train_labels, epochs=4,
                    validation_data=(test_images, test_labels))

test_loss, test_acc = model.evaluate(test_images,  test_labels, verbose=2)
print(test_acc)

from keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# creates a data generator object that transforms images
datagen = ImageDataGenerator(
rotation_range=40,
width_shift_range=0.2,
height_shift_range=0.2,
shear_range=0.2,
zoom_range=0.2,
horizontal_flip=True,
fill_mode='nearest')

# pick an image to transform
test_img = train_images[20]
img = image.img_to_array(test_img)  # convert image to numpy arry
img = img.reshape((1,) + img.shape)  # reshape image

i = 0

for batch in datagen.flow(img, save_prefix='test', save_format='jpeg'):  # this loops runs forever until we break, saving images to current directory with specified prefix
    plt.figure(i)
    plot = plt.imshow(image.img_to_array(batch[0]))
    i += 1
    if i > 4:  # show 4 images
        break

plt.show()

#Imports
import os
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
keras = tf.keras

import tensorflow_datasets as tfds
tfds.disable_progress_bar()

# split the data manually into 80% training, 10% testing, 10% validation
(raw_train, raw_validation, raw_test), metadata = tfds.load(
    'cats_vs_dogs',
    split=['train[:80%]', 'train[80%:90%]', 'train[90%:]'],
    with_info=True,
    as_supervised=True,
)

get_label_name = metadata.features['label'].int2str  # creates a function object that we can use to get labels

# display 2 images from the dataset
for image, label in raw_train.take(5):
  plt.figure()
  plt.imshow(image)
  plt.title(get_label_name(label))

# display 2 images from the dataset
for image, label in raw_train.take(2):
  plt.figure()
  plt.imshow(image)
  plt.title(get_label_name(label))

IMG_SIZE = 160 # All images will be resized to 160x160

def format_example(image, label):
  """
  returns an image that is reshaped to IMG_SIZE
  """
  image = tf.cast(image, tf.float32)
  image = (image/127.5) - 1
  image = tf.image.resize(image, (IMG_SIZE, IMG_SIZE))
  return image, label

train = raw_train.map(format_example)
validation = raw_validation.map(format_example)
test = raw_test.map(format_example)

for image, label in train.take(2):
  plt.figure()
  plt.imshow(image)
  plt.title(get_label_name(label))

BATCH_SIZE = 32
SHUFFLE_BUFFER_SIZE = 1000

train_batches = train.shuffle(SHUFFLE_BUFFER_SIZE).batch(BATCH_SIZE)
validation_batches = validation.batch(BATCH_SIZE)
test_batches = test.batch(BATCH_SIZE)

for img, label in raw_train.take(2):
  print("Original shape:", img.shape)

for img, label in train.take(2):
  print("New shape:", img.shape)

IMG_SHAPE = (IMG_SIZE, IMG_SIZE, 3)

# Create the base model from the pre-trained model MobileNet V2
base_model = tf.keras.applications.MobileNetV2(input_shape=IMG_SHAPE,
                                               include_top=False,
                                               weights='imagenet')

base_model.summary()

for image, _ in train_batches.take(1):
   pass

feature_batch = base_model(image)
print(feature_batch.shape)

base_model.trainable = False

base_model.summary()

global_average_layer = tf.keras.layers.GlobalAveragePooling2D()

prediction_layer = keras.layers.Dense(1)

model = tf.keras.Sequential([
  base_model,
  global_average_layer,
  prediction_layer
])

model.summary()

base_learning_rate = 0.0001
model.compile(optimizer=tf.keras.optimizers.RMSprop(learning_rate=base_learning_rate),
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

# We can evaluate the model right now to see how it does before training it on our new images
initial_epochs = 3
validation_steps=20

loss0,accuracy0 = model.evaluate(validation_batches, steps = validation_steps)

# Now we can train it on our images
history = model.fit(train_batches,
                    epochs=initial_epochs,
                    validation_data=validation_batches)

acc = history.history['accuracy']
print(acc)

model.save("dogs_vs_cats.h5")  # we can save the model and reload it at anytime in the future
new_model = tf.keras.models.load_model('dogs_vs_cats.h5')

